[package]
name = "figma-agent-fontconfig-sys"
version = "0.0.0"
edition = "2021"

[lib]
name = "fontconfig_sys"

[dependencies]
figma-agent-freetype-sys = { path = "../freetype-sys" }
libc = "0.2.126"

[build-dependencies]
bindgen = "0.60.1"
pkg-config = "0.3.25"
