[package]
name = "figma-agent-fontconfig-sys"
version = "0.3.2"
edition = "2021"

[lib]
name = "fontconfig_sys"

[dependencies]
figma-agent-freetype-sys = { path = "../freetype-sys" }
libc = "=0.2.152"

[build-dependencies]
bindgen = "=0.69.4"
pkg-config = "=0.3.29"
