[package]
name = "figma-agent-fontconfig-sys"
version = "0.2.5"
edition = "2021"

[lib]
name = "fontconfig_sys"

[dependencies]
figma-agent-freetype-sys = { path = "../freetype-sys" }
libc = "0.2.139"

[build-dependencies]
bindgen = "0.63.0"
pkg-config = "0.3.26"
