[package]
name = "figma-agent"
version = "0.4.3"
edition = "2024"

[dependencies]
anyhow = "=1.0.100"
axum = "=0.8.7"
fontconfig-parser = "=0.5.8"
harfrust = "=0.4.0"
interp = "=2.1.1"
itertools = "=0.14.0"
jsonc-parser = { version = "=0.28.0", features = ["serde"] }
listenfd = "=1.0.2"
read-fonts = "=0.36.0"
serde = { version = "=1.0.228", features = ["derive"] }
serde_json = "=1.0.145"
skrifa = "=0.39.0"
svg = "=0.18.0"
thiserror = "=2.0.17"
tokio = { version = "=1.48.0", features = ["full"] }
tower = { version = "=0.5.2", features = ["full"] }
tower-http = { version = "=0.6.7", features = ["full"] }
tracing = "=0.1.43"
tracing-subscriber = "=0.3.22"
walkdir = "=2.5.0"
xdg = "=3.0.0"
