[package]
name = "figma-agent-freetype-sys"
version = "0.0.0"
edition = "2021"

[lib]
name = "freetype_sys"

[dependencies]
libc = "0.2.126"

[build-dependencies]
bindgen = "0.60.1"
pkg-config = "0.3.25"
