[package]
name = "figma-agent-freetype-sys"
version = "0.2.0"
edition = "2021"

[lib]
name = "freetype_sys"

[dependencies]
libc = "0.2.136"

[build-dependencies]
bindgen = "0.61.0"
pkg-config = "0.3.25"
