[package]
name = "figma-agent-freetype-sys"
version = "0.2.8"
edition = "2021"

[lib]
name = "freetype_sys"

[dependencies]
libc = "0.2.151"

[build-dependencies]
bindgen = "0.68.1"
pkg-config = "0.3.28"
