[package]
name = "figma-agent-freetype-sys"
version = "0.3.2"
edition = "2021"

[lib]
name = "freetype_sys"

[dependencies]
libc = "=0.2.152"

[build-dependencies]
bindgen = "=0.69.2"
pkg-config = "=0.3.28"
