[package]
name = "figma-agent"
version = "0.2.2"
edition = "2021"

[dependencies]
actix-cors = "0.6.4"
actix-files = "0.6.2"
actix-web = "4.2.1"
env_logger = "0.10.0"
figma-agent-fontconfig = { path = "../fontconfig" }
figma-agent-freetype = { path = "../freetype" }
itertools = "0.10.5"
lazy_static = "1.4.0"
parking_lot = "0.12.1"
serde = { version = "1.0.148", features = ["derive"] }
serde_json = "1.0.89"
xdg = "2.4.1"
