[package]
name = "figma-agent-fontconfig"
version = "0.2.3"
edition = "2021"

[lib]
name = "fontconfig"

[dependencies]
figma-agent-fontconfig-sys = { path = "../fontconfig-sys" }
figma-agent-freetype = { path = "../freetype" }
libc = "0.2.138"
